<script setup lang="ts">
import {onMounted,reactive,ref,computed} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api,message} from '../api/client'
import {modelTypes,type Mapping} from '../api/models'
const props=defineProps<{providerId:number;enabled:boolean;category?:string|null}>()
const allowed=computed(()=>Object.entries(modelTypes).filter(([t])=>!props.category||(props.category==='multimodal'?t==='multimodal':props.category==='text'?['text','reasoning','multimodal'].includes(t):props.category==='image'?t==='image':['embedding','rerank'].includes(t))))
const rows=ref<Mapping[]>([]),discovered=ref<string[]>([]),loading=ref(false),discovering=ref(false),dialog=ref(false),saving=ref(false),editing=ref<number|null>(null),error=ref('')
const blank=()=>({logical_model:'',upstream_model:'',model_type:props.category==='multimodal'?'multimodal':props.category==='image'?'image':props.category==='vector'?'embedding':'text',status:'enabled'})
const form=reactive(blank()),base=()=>'/admin/providers/'+props.providerId+'/model-mappings'
async function load(){loading.value=true;error.value='';try{rows.value=(await api.get(base())).data.data}catch(e){error.value=message(e)}finally{loading.value=false}}
async function discover(){discovering.value=true;try{const r=(await api.post('/admin/providers/'+props.providerId+'/discover-models')).data.data;discovered.value=r.models.map((m:{id:string})=>m.id);ElMessage.success('发现 '+discovered.value.length+' 个真实模型')}catch(e){ElMessage.error(message(e))}finally{discovering.value=false}}
function open(m?:Mapping){editing.value=m?.id??null;Object.assign(form,blank(),m?{logical_model:m.logical_model,upstream_model:m.upstream_model,model_type:m.model_type,status:m.status}:{});dialog.value=true}
function suggestions(q:string,cb:(items:{value:string}[])=>void){cb(discovered.value.filter(n=>n.toLowerCase().includes(q.toLowerCase())).slice(0,50).map(value=>({value})))}
async function save(){saving.value=true;try{if(editing.value)await api.put(base()+'/'+editing.value,form);else await api.post(base(),form);dialog.value=false;await load();ElMessage.success('映射已保存')}catch(e){ElMessage.error(message(e))}finally{saving.value=false}}
async function toggle(m:Mapping){try{await api.put(base()+'/'+m.id,{logical_model:m.logical_model,upstream_model:m.upstream_model,model_type:m.model_type,status:m.status==='enabled'?'disabled':'enabled'});await load()}catch(e){ElMessage.error(message(e))}}
async function remove(m:Mapping){try{await ElMessageBox.confirm('删除后此映射不再参与候选查询，模型组中的逻辑名保留。','删除模型映射',{type:'warning',confirmButtonText:'删除',cancelButtonText:'取消'});await api.delete(base()+'/'+m.id);await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(message(e))}}
onMounted(load)
</script>
<template><div class="panel"><h2>模型映射</h2><p class="muted">将客户端使用的逻辑名称映射到此账号的真实模型。</p><el-alert v-if="error" :title="error" type="error" :closable="false"/><div class="toolbar"><el-button :loading="discovering" :disabled="!enabled" @click="discover">发现模型</el-button><el-button type="primary" :disabled="rows.length>=100" @click="open()">新增映射</el-button><span class="muted">{{discovered.length?'已发现 '+discovered.length+' 个模型，可在真实模型输入框选择':'也可手工填写真实模型名称'}}</span></div><el-table :data="rows" v-loading="loading" empty-text="暂无模型映射"><el-table-column prop="logical_model" label="逻辑模型" min-width="150"/><el-table-column prop="upstream_model" label="真实模型" min-width="160"/><el-table-column label="类型" width="110"><template #default="s">{{modelTypes[s.row.model_type]}}</template></el-table-column><el-table-column label="状态" width="85"><template #default="s"><el-tag :type="s.row.status==='enabled'?'success':'info'">{{s.row.status==='enabled'?'启用':'禁用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="160"><template #default="s"><el-button link type="primary" @click="open(s.row)">编辑</el-button><el-button link @click="toggle(s.row)">{{s.row.status==='enabled'?'禁用':'启用'}}</el-button><el-button link type="danger" :disabled="rows.length<=1" @click="remove(s.row)">删除</el-button></template></el-table-column></el-table><el-dialog v-model="dialog" :title="editing?'编辑映射':'新增映射'" width="540px"><el-form label-width="95px"><el-form-item label="逻辑模型"><el-input v-model="form.logical_model" placeholder="客户端使用的名称，例如 business-chat" maxlength="100"/></el-form-item><el-form-item label="真实模型"><el-autocomplete v-model="form.upstream_model" :fetch-suggestions="suggestions" placeholder="手工填写或选择已发现的模型" maxlength="200" style="width:100%"/></el-form-item><el-form-item label="模型类型"><el-select v-model="form.model_type"><el-option v-for="[value,label] in allowed" :key="value" :value="value" :label="label"/></el-select></el-form-item><el-form-item label="状态"><el-select v-model="form.status"><el-option label="启用" value="enabled"/><el-option label="禁用" value="disabled"/></el-select></el-form-item><p class="muted">同一逻辑名在多个账号中的类型必须一致。修改逻辑名后，请检查模型组成员。</p></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></div></template>
