<script setup lang="ts">
import {formatDate} from '../ui/branding'
import {ref,watch} from 'vue'
import {useRoute} from 'vue-router'
import {api,message} from '../api/client'
const route=useRoute(),row=ref<any>(null),error=ref(''),loading=ref(false)
const labels:Record<string,string>={success:'成功',failure:'失败',client_cancelled:'客户端取消',started:'开始调用',not_sent:'未发送'}
const stages:Record<string,string>={authentication:'认证',user_validation:'用户校验',group_validation:'用户组校验',model_permission:'模型权限',compliance:'内容审核入口',smart_routing:'智能路由入口',model_selection:'模型选择',provider_scheduler:'账号调度',quota:'配额',concurrency:'四级并发',provider_concurrency:'账号占用',protocol_adapter:'协议适配',upstream:'上游调用',usage:'用量记录',call_log:'终态日志',request_validation:'请求格式校验'}
let generation=0
async function load(){const mine=++generation;loading.value=true;row.value=null;error.value='';try{const d=(await api.get('/admin/call-logs/'+encodeURIComponent(String(route.params.requestId)))).data.data;if(mine===generation)row.value=d}catch(e){if(mine===generation)error.value=message(e)}finally{if(mine===generation)loading.value=false}}
watch(()=>route.params.requestId,load,{immediate:true})
</script>
<template><div v-loading="loading"><router-link class="detail-link" :to="{path:'/admin/call-logs',query:{request_id:String(route.params.requestId)}}">← 返回此请求的列表</router-link><h1 style="margin-top:20px">调用详情</h1><el-alert v-if="error" :title="error" type="error" :closable="false"/>
<template v-if="row"><p class="request-id">{{row.request_id}}</p><div class="performance-kpis"><div v-for="k in [{name:'TTFT · ms',value:row.ttft_ms},{name:'总耗时 · ms',value:row.gateway_latency_ms},{name:'上游耗时 · ms',value:row.upstream_latency_ms},{name:'Tokens/s',value:row.tokens_per_second}]" :key="k.name"><span class="muted">{{k.name}}</span><strong>{{k.value==null?'—':Number(k.value).toLocaleString()}}</strong></div></div><div class="panel"><h2>基本信息与认证</h2><el-descriptions :column="2" border><el-descriptions-item label="时间">{{formatDate(row.created_at)}}</el-descriptions-item><el-descriptions-item label="状态">{{labels[row.status]}} · HTTP {{row.http_status}}</el-descriptions-item><el-descriptions-item label="操作 / 模式">{{row.operation}} / {{row.stream?'SSE':'JSON'}}</el-descriptions-item><el-descriptions-item label="客户端 IP">{{row.client_ip||'—'}}</el-descriptions-item><el-descriptions-item label="用户">{{row.username_snapshot||'未认证'}} · #{{row.user_id??'—'}}</el-descriptions-item><el-descriptions-item label="用户组">{{row.group_name_snapshot||'—'}} · #{{row.user_group_id??'—'}}</el-descriptions-item><el-descriptions-item label="API Key">{{row.key_name_snapshot||'—'}} · #{{row.api_key_id??'—'}}</el-descriptions-item><el-descriptions-item label="认证结果">{{row.trace.authentication==='authenticated'?'已认证':'未完成认证'}}</el-descriptions-item></el-descriptions></div>
<div class="panel"><h2>模型选择与账号</h2><el-descriptions :column="2" border><el-descriptions-item label="请求模型">{{row.request_model||'—'}}</el-descriptions-item><el-descriptions-item label="最终逻辑模型">{{row.logical_model||'—'}}</el-descriptions-item><el-descriptions-item label="上游模型">{{row.upstream_model||'—'}}</el-descriptions-item><el-descriptions-item label="账号 / 协议">{{row.provider_name_snapshot||'未选择'}} · #{{row.provider_id??'—'}} / {{row.protocol||'—'}} <router-link v-if="row.provider_id" class="detail-link" :to="'/admin/providers/'+row.provider_id">查看账号</router-link></el-descriptions-item><el-descriptions-item label="授权模型组" :span="2"><span v-for="g in row.trace.model_groups" :key="g.id">{{g.name}} (#{{g.id}})　</span><span v-if="!row.trace.model_groups.length">—</span></el-descriptions-item></el-descriptions></div>
<div class="panel"><h2>请求链路与 Failover</h2><p v-if="row.trace.parent_request_id"><router-link class="detail-link" :to="'/admin/call-logs/'+row.trace.parent_request_id">查看Embedding关联的父请求 →</router-link></p><p class="muted">以下按执行顺序展示进入的阶段；入口被执行不代表后续功能已实现。</p><div class="stage-list"><el-tag v-for="(s,i) in row.trace.stages" :key="i" type="info">{{i+1}}. {{stages[s]||s}}</el-tag></div><el-table :data="row.trace.attempts" empty-text="未发送上游请求"><el-table-column label="顺序" width="70"><template #default="s">{{s.$index+1}}</template></el-table-column><el-table-column prop="provider_name" label="账号快照"/><el-table-column prop="logical_model" label="逻辑模型"/><el-table-column prop="upstream_model" label="上游模型"/><el-table-column label="结果" width="130"><template #default="s">{{labels[s.row.status]||s.row.status}}</template></el-table-column><el-table-column prop="http_status" label="上游 HTTP" width="110"/><el-table-column prop="code" label="错误码" min-width="170"/><el-table-column label="耗时" width="120"><template #default="s">{{s.row.elapsed_ms==null?'—':s.row.elapsed_ms+' ms'}}</template></el-table-column><template #empty><EmptyState title="未发送上游请求" description="检查筛选条件、时间范围或相关配置后重试。"/></template></el-table></div>
<div class="panel"><h2>Token 与性能</h2><el-descriptions :column="3" border><el-descriptions-item label="输入 Token">{{row.input_tokens??'未上报'}}</el-descriptions-item><el-descriptions-item label="输出 Token">{{row.output_tokens??'未上报'}}</el-descriptions-item><el-descriptions-item label="缓存 Token">{{row.cached_tokens??'未上报'}}</el-descriptions-item><el-descriptions-item label="总 Token">{{row.total_tokens??'未上报'}}</el-descriptions-item><el-descriptions-item label="Gateway 总耗时">{{row.gateway_latency_ms}} ms</el-descriptions-item><el-descriptions-item label="上游尝试耗时合计">{{row.upstream_latency_ms==null?'未调用':row.upstream_latency_ms+' ms'}}</el-descriptions-item><el-descriptions-item label="TTFT">{{row.ttft_ms==null?'不可用':row.ttft_ms+' ms'}}</el-descriptions-item><el-descriptions-item label="Tokens/s">{{row.tokens_per_second??'不可用'}}</el-descriptions-item><el-descriptions-item label="排队耗时">{{row.trace.queue_wait_ms}} ms</el-descriptions-item></el-descriptions><p class="muted">Token 仅记录上游上报值。TTFT 仅在流式首个有效内容块被观测时可用；非流式 Tokens/s 使用上游整包响应时长。SSE 开始后失败时 HTTP 仍为 200，请以终态和错误码判断。</p></div>
<div v-if="row.request_body!=null||row.response_body!=null" class="panel"><h2>脱敏正文预览</h2><h3>请求</h3><pre style="white-space:pre-wrap;overflow-wrap:anywhere">{{JSON.stringify(row.request_body,null,2)}}</pre><h3>响应</h3><pre style="white-space:pre-wrap;overflow-wrap:anywhere">{{JSON.stringify(row.response_body,null,2)}}</pre></div><div class="panel"><h2>错误、智能路由与内容审核</h2><el-descriptions :column="1" border><el-descriptions-item label="错误码">{{row.error_code||'—'}}</el-descriptions-item><el-descriptions-item label="错误信息">{{row.error_message||'—'}}</el-descriptions-item><el-descriptions-item label="智能路由"><template v-if="row.trace.smart_routing&&typeof row.trace.smart_routing==='object'">{{row.trace.smart_routing.status}} · {{row.trace.smart_routing.classification||row.trace.smart_routing.reason}} <router-link class="detail-link" :to="{path:'/admin/smart-route/logs',query:{request_id:row.request_id}}">查看路由决策</router-link></template><template v-else>{{row.trace.smart_routing==='not_applicable'?'未使用虚拟模型':row.trace.smart_routing==='sample_vectorization'?'管理员样本向量化':row.trace.smart_routing==='stage16'?'历史版本未启用':'未到达'}}</template></el-descriptions-item><el-descriptions-item label="内容审核"><template v-if="row.trace.compliance&&typeof row.trace.compliance==='object'">{{row.trace.compliance.action==='block'?'已阻断':row.trace.compliance.action==='audit'?'审核命中并继续':'审核通过'}} · {{row.trace.compliance.elapsed_ms}} ms <router-link class="detail-link" :to="{path:'/admin/compliance/logs',query:{request_id:row.request_id}}">查看审核证据</router-link><span v-if="row.trace.compliance.log_delivery==='pending'"> · 审核日志待入库</span><span v-if="row.trace.compliance.log_delivery==='unavailable'"> · 审核日志不可用</span></template><template v-else>{{row.trace.compliance==='stage17'?'历史版本未启用':row.trace.compliance==='not_applicable'?'无适用策略':row.trace.compliance==='parent_checked'?'父请求已审核':row.trace.compliance==='preflight_not_checked'?'预检未审核内容':'未到达'}}</template></el-descriptions-item></el-descriptions><p class="muted">历史快照在关联对象删除后仍保留。正文默认不保存；开启日志预览后仅展示脱敏且有限的正文。密钥和认证头不保存。</p></div></template></div></template>
<style scoped>.request-id{font-family:monospace;overflow-wrap:anywhere}.detail-link{color:var(--el-color-primary)}.stage-list{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0 24px}.performance-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.performance-kpis>div{background:var(--surface);border:1px solid var(--line);border-radius:8px;padding:20px}.performance-kpis strong{display:block;font-size:28px;margin-top:10px}@media(max-width:900px){.performance-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}}</style>
