<script setup lang="ts">
import {formatDate} from '../ui/branding'
import {computed,reactive,ref,watch,onUnmounted} from 'vue'
import {useRoute} from 'vue-router'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api,message} from '../api/client'
const route=useRoute(),view=computed(()=>route.path.split('/').pop()||'words')
const rows=ref<any[]>([]),words=ref<any[]>([]),samples=ref<any[]>([]),groups=ref<any[]>([]),models=ref<any[]>([]),loading=ref(false),error=ref(''),saving=ref(false),dialog=ref(false),editing=ref<number|null>(null),detail=ref<any>(null)
const page=ref(1),total=ref(0),requestId=ref(''),status=ref(''),days=ref(7),range=ref<[Date,Date]|null>(null)
const labels:Record<string,string>={text:'普通文本',wildcard:'通配符',regex:'正则',low:'低',medium:'中',high:'高',critical:'严重',enabled:'启用',disabled:'禁用',pending:'待向量化',processing:'处理中',ready:'就绪',failed:'失败',audit:'Audit · 记录并继续',block:'Block · 拒绝请求',word:'敏感词',sample:'语义样本'}
const blank=()=>({pattern:'',kind:'text',risk:'medium',status:'enabled',text:'',name:'',action:'audit',word_ids:[] as number[],sample_ids:[] as number[],group_ids:[] as number[],models:[] as string[],threshold:.85})
const form=reactive(blank())
let generation=0
async function load(){const mine=++generation;loading.value=true;error.value='';try{
 const params:any={page:page.value}
 if(view.value==='logs'){params.request_id=requestId.value||undefined;params.action=status.value||undefined;const end=range.value?.[1]||new Date(),start=range.value?.[0]||new Date(end.getTime()-days.value*86400000);params.start=start.toISOString();params.end=end.toISOString()}
 if(view.value==='samples')params.status=status.value||undefined
 const d=(await api.get('/admin/compliance/'+view.value,{params})).data.data
 if(mine!==generation)return;rows.value=d.items;total.value=d.total||d.items.length
 if(view.value==='policies'){
 const [w,g,m]=await Promise.all([api.get('/admin/compliance/words'),api.get('/admin/user-group-options'),api.get('/admin/logical-models')]);if(mine!==generation)return
 words.value=w.data.data.items;groups.value=g.data.data.items||g.data.data;models.value=m.data.data.data||m.data.data
 let all:any[]=[];for(let p=1;p<=25;p++){const s=(await api.get('/admin/compliance/samples',{params:{page:p}})).data.data;all=all.concat(s.items);if(all.length>=s.total)break}if(mine===generation)samples.value=all
 }
 }catch(e){if(mine===generation)error.value=message(e)}finally{if(mine===generation)loading.value=false}}
function open(row?:any){editing.value=row?.id||null;Object.assign(form,blank(),row||{});if(view.value==='policies'&&!row)form.status='disabled';dialog.value=true}
async function save(){saving.value=true;try{let body:any
 if(view.value==='words')body={pattern:form.pattern,kind:form.kind,risk:form.risk,status:form.status}
 else if(view.value==='samples')body={text:form.text,risk:form.risk}
 else body={name:form.name,action:form.action,status:form.status,word_ids:form.word_ids,sample_ids:form.sample_ids,group_ids:form.group_ids,models:form.models,threshold:form.threshold}
 await api[editing.value?'put':'post']('/admin/compliance/'+view.value+(editing.value?'/'+editing.value:''),body);ElMessage.success('已保存');dialog.value=false;await load()
 }catch(e){ElMessage.error(message(e))}finally{saving.value=false}}
async function remove(row:any){try{await ElMessageBox.confirm('删除此资源？已被策略引用的词或样本须先移除引用。历史审核日志保留。','删除资源',{type:'warning'});await api.delete('/admin/compliance/'+view.value+'/'+row.id);ElMessage.success('已删除');await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(message(e))}}
async function retry(row:any){try{await api.post('/admin/compliance/samples/'+row.id+'/vectorize');ElMessage.success('已重新排队');await load()}catch(e){ElMessage.error(message(e))}}
function logRisk(row:any){const risks=(row.matches||[]).flatMap((m:any)=>(m.evidence||[]).map((e:any)=>e.risk));return ['critical','high','medium','low'].find(r=>risks.includes(r))||''}
function names(ids:number[],source:any[]){return ids.map(i=>source.find(x=>x.id===i)?.name||source.find(x=>x.id===i)?.pattern||'样本 #'+i).join('、')||'—'}
watch(()=>route.fullPath,()=>{page.value=1;status.value='';requestId.value=String(route.query.request_id||'');load()},{immediate:true})
const timer=window.setInterval(()=>{if(view.value==='samples'&&!dialog.value&&!loading.value)load()},5000)
onUnmounted(()=>{clearInterval(timer);generation++})
</script>
<template><div><PageHeader title="内容合规" description="在智能路由及上游调用前审核文本。语义检查使用本地多语言模型，Block命中不会调用Provider或产生模型Token费用。"/><div class="toolbar"><router-link v-for="(label,k) in {words:'敏感词',samples:'审核样本',policies:'策略组',logs:'审核日志'}" :key="k" :to="'/admin/compliance/'+k"><el-button :type="view===k?'primary':'default'">{{label}}</el-button></router-link></div><el-alert v-if="error" :title="error" type="error" :closable="false"/><div class="panel"><div class="toolbar"><template v-if="view==='logs'"><el-input v-model="requestId" clearable placeholder="精确Request ID" style="width:280px"/><el-select v-model="status" clearable placeholder="全部动作" style="width:170px"><el-option label="Audit" value="audit"/><el-option label="Block" value="block"/></el-select><el-select v-model="days" style="width:130px" @change="range=null"><el-option v-for="d in [1,7,30]" :key="d" :label="'最近'+d+'天'" :value="d"/></el-select><el-date-picker v-model="range" type="datetimerange" start-placeholder="开始时间" end-placeholder="结束时间"/></template><el-select v-if="view==='samples'" v-model="status" clearable placeholder="全部向量状态" style="width:180px"><el-option v-for="s in ['pending','processing','ready','failed']" :key="s" :label="labels[s]" :value="s"/></el-select><el-button @click="page=1;load()">查询</el-button><el-button v-if="view!=='logs'" type="primary" @click="open()">新增{{view==='words'?'敏感词':view==='samples'?'审核样本':'策略'}}</el-button></div>
<p v-if="view==='samples'" class="muted">本地模型离线向量化；失败样本不参与检索。更新已启用策略引用的样本会暂时拒绝相关请求，直到向量重新就绪。</p><p v-if="view==='policies'" class="muted">未选择用户组或模型时适用于全部。Block优先于Audit；被引用的资源须先移除引用才能删除。</p>
<el-table :data="rows" v-loading="loading" empty-text="暂无记录"><el-table-column prop="id" label="ID" width="65"/>
<template v-if="view==='words'"><el-table-column prop="pattern" label="规则" min-width="240" show-overflow-tooltip/><el-table-column label="匹配方式" width="120"><template #default="s">{{labels[s.row.kind]}}</template></el-table-column><el-table-column label="状态" width="90"><template #default="s">{{labels[s.row.status]}}</template></el-table-column></template>
<template v-if="view==='samples'"><el-table-column prop="text" label="样本文本" min-width="280" show-overflow-tooltip/><el-table-column label="向量状态" width="130"><template #default="s"><el-tag :type="s.row.vector_status==='ready'?'success':s.row.vector_status==='failed'?'danger':'info'">{{labels[s.row.vector_status]}}</el-tag></template></el-table-column><el-table-column prop="vector_error" label="错误码" min-width="180"/></template>
<el-table-column v-if="view==='words'||view==='samples'" label="风险级别" width="90"><template #default="s"><el-tag :type="s.row.risk==='high'?'danger':s.row.risk==='medium'?'warning':'success'">{{labels[s.row.risk]}}</el-tag></template></el-table-column>
<template v-if="view==='policies'"><el-table-column prop="name" label="策略名称" min-width="140"/><el-table-column label="动作" min-width="190"><template #default="s"><el-tag :type="s.row.action==='block'?'danger':'warning'">{{labels[s.row.action]}}</el-tag></template></el-table-column><el-table-column label="规则数" width="90"><template #default="s">{{s.row.word_ids.length+s.row.sample_ids.length}}</template></el-table-column><el-table-column label="适用用户组" min-width="150"><template #default="s">{{s.row.group_ids.length?names(s.row.group_ids,groups):'全部'}}</template></el-table-column><el-table-column label="状态" width="90"><template #default="s">{{labels[s.row.status]}}</template></el-table-column></template>
<template v-if="view==='logs'"><el-table-column label="Request ID" min-width="290"><template #default="s"><router-link style="color:var(--el-color-primary)" :to="{path:'/admin/call-logs',query:{request_id:s.row.request_id}}">{{s.row.request_id}}</router-link></template></el-table-column><el-table-column prop="model" label="请求模型" min-width="140"/><el-table-column label="用户" width="95"><template #default="s">#{{s.row.user_id??'—'}}</template></el-table-column><el-table-column label="风险" width="90"><template #default="s"><el-tag v-if="logRisk(s.row)" :type="['high','critical'].includes(logRisk(s.row))?'danger':logRisk(s.row)==='medium'?'warning':'success'">{{labels[logRisk(s.row)]}}</el-tag><span v-else>—</span></template></el-table-column><el-table-column label="命中策略" min-width="160"><template #default="s">{{s.row.matches?.map((m:any)=>m.policy_name).join('、')||'—'}}</template></el-table-column><el-table-column label="动作" min-width="190"><template #default="s"><el-tag :type="s.row.action==='block'?'danger':'warning'">{{labels[s.row.action]}}</el-tag></template></el-table-column><el-table-column prop="elapsed_ms" label="审核耗时 ms" width="125"/><el-table-column label="时间" min-width="180"><template #default="s">{{formatDate(s.row.created_at)}}</template></el-table-column><el-table-column width="100" label="详情"><template #default="s"><el-button link type="primary" @click="detail=s.row">命中证据</el-button></template></el-table-column></template>
<el-table-column v-else label="操作" width="230" fixed="right"><template #default="s"><el-button link type="primary" @click="open(s.row)">编辑</el-button><el-button v-if="view==='samples'" link @click="retry(s.row)">重新向量化</el-button><el-button link type="danger" @click="remove(s.row)">删除</el-button></template></el-table-column><template #empty><EmptyState title="暂无记录" description="检查筛选条件、时间范围或相关配置后重试。"/></template></el-table><el-pagination v-if="view==='samples'||view==='logs'" v-model:current-page="page" :total="total" :page-size="20" layout="total, prev, pager, next" @current-change="load" style="margin-top:24px"/></div>
<el-drawer v-model="dialog" :title="(editing?'编辑':'新增')+(view==='words'?'敏感词':view==='samples'?'审核样本':'策略')" size="640px"><el-form label-width="100px"><template v-if="view==='words'"><el-form-item label="规则"><el-input v-model="form.pattern" maxlength="256"/></el-form-item><el-form-item label="匹配方式"><el-select v-model="form.kind"><el-option v-for="k in ['text','wildcard','regex']" :key="k" :value="k" :label="labels[k]"/></el-select></el-form-item><p class="muted">普通文本忽略大小写并进行Unicode规范化；通配符*匹配任意字符，?匹配单个字符，按文本片段匹配。正则有执行时限，超时拒绝请求。</p></template><el-form-item v-if="view==='samples'" label="样本文本"><el-input v-model="form.text" type="textarea" :rows="5" maxlength="2000" show-word-limit/></el-form-item><el-form-item v-if="view!=='policies'" label="风险级别"><el-select v-model="form.risk"><el-option v-for="r in ['low','medium','high']" :key="r" :value="r" :label="labels[r]"/></el-select></el-form-item><template v-if="view==='policies'"><el-form-item label="名称"><el-input v-model="form.name" maxlength="80"/></el-form-item><el-form-item label="动作"><el-select v-model="form.action"><el-option v-for="a in ['audit','block']" :key="a" :value="a" :label="labels[a]"/></el-select></el-form-item><el-alert v-if="form.action==='block'" title="Block命中会直接拒绝适用范围内的请求。请确认规则及范围，避免误阻断正常业务。" type="warning" :closable="false"/><el-form-item label="敏感词"><el-select v-model="form.word_ids" multiple filterable style="width:100%"><el-option v-for="w in words" :key="w.id" :value="w.id" :label="w.pattern+' · '+labels[w.status]"/></el-select></el-form-item><el-form-item label="审核样本"><el-select v-model="form.sample_ids" multiple filterable style="width:100%"><el-option v-for="s in samples" :key="s.id" :value="s.id" :label="s.text.slice(0,45)+' · '+labels[s.vector_status]"/></el-select></el-form-item><el-form-item label="语义阈值"><el-input-number v-model="form.threshold" :min="0" :max="1" :step=".01" :precision="2"/></el-form-item><el-form-item label="用户组"><el-select v-model="form.group_ids" multiple filterable style="width:100%" placeholder="全部用户组"><el-option v-for="g in groups" :key="g.id" :value="g.id" :label="g.name"/></el-select></el-form-item><el-form-item label="模型"><el-select v-model="form.models" multiple filterable style="width:100%" placeholder="全部模型"><el-option v-for="m in models" :key="m.name" :value="m.name" :label="m.name"/></el-select></el-form-item></template><el-form-item v-if="view!=='samples'" label="状态"><el-select v-model="form.status"><el-option label="启用" value="enabled"/><el-option label="禁用" value="disabled"/></el-select></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-drawer>
<el-dialog :model-value="!!detail" title="审核命中证据" width="720px" @close="detail=null"><template v-if="detail"><p>{{detail.request_id}} · {{labels[detail.action]}}</p><div v-for="(m,i) in detail.matches" :key="i"><h3>{{m.policy_name}} · {{labels[m.action]}}</h3><el-table :data="m.evidence"><el-table-column prop="id" label="规则/样本ID"/><el-table-column label="来源"><template #default="s">{{labels[s.row.source]}}</template></el-table-column><el-table-column label="风险"><template #default="s"><el-tag :type="s.row.risk==='high'?'danger':s.row.risk==='medium'?'warning':'success'">{{labels[s.row.risk]}}</el-tag></template></el-table-column><el-table-column label="相似度"><template #default="s">{{s.row.similarity?.toFixed(6)||'—'}}</template></el-table-column></el-table><p class="muted">共{{m.hit_count}}条命中，最多展示20条证据。</p></div><p class="muted">仅保存策略及规则/样本快照，不保存客户端正文、匹配原文或生成内容。</p></template></el-dialog></div></template>
