<script setup lang="ts">
import {branding,formatDate} from '../ui/branding'
import {computed,ref,watch,nextTick,onMounted,onBeforeUnmount,type ComponentPublicInstance} from 'vue'
import * as echarts from 'echarts'
import {dark,chartTheme} from '../ui/preferences'
import {useRouter} from 'vue-router'
import {api,message} from '../api/client'
const router=useRouter(),period=ref('24h'),data=ref<any>(null),loading=ref(false),error=ref(''),auto=ref(true)
const providerMetadata=ref<Record<number,any>>({})
function providerFailure(id:number){const row=data.value?.rankings.provider.find((r:any)=>r.provider_id===id&&!r.other);return row&&row.requests?((row.failure/row.requests)*100).toFixed(1)+'%':'—'}
let stopped=false,timer:ReturnType<typeof setInterval>|undefined
const charts:Record<string,echarts.ECharts>={},hosts:Record<string,HTMLElement>={}
const specs=[{id:'tokens',title:'Token 趋势'},{id:'requests',title:'请求趋势'},{id:'concurrency',title:'并发趋势 · 已采样峰值'},{id:'failures',title:'失败趋势'},{id:'provider',title:'Provider 排行 · 已上报 Token'},{id:'model',title:'模型排行 · 已上报 Token'}]
const health:Record<string,string>={healthy:'健康',unhealthy:'异常',unknown:'未验证'},schedule:Record<string,string>={Available:'可用',Cooling:'冷却中',Unavailable:'不可用',Disabled:'禁用'}
function bindChart(key:string,node:Element|ComponentPublicInstance|null){if(node instanceof HTMLElement)hosts[key]=node}
function number(value:any){return value==null?'不可用':Number(value).toLocaleString()}
const cards=computed(()=>data.value?[
{label:'当前并发',value:data.value.live.active},
{label:'等待队列',value:data.value.live.queued},
{label:'今日请求',value:data.value.today.requests},
{label:'今日 Token · 已上报',value:data.value.today.total_tokens},
{label:'失败 / 取消 · 所选时段',value:data.value.summary.failure,failed:true},
{label:'活跃用户 · 所选时段',value:data.value.summary.active_users}]:[])
function usage(query:Record<string,string>={}){return {path:'/admin/usage',query:{start:data.value.start,end:data.value.end,grain:data.value.grain,...query}}}
function failed(){return {path:'/admin/call-logs',query:{start:data.value.start,end:data.value.end,status:'failed'}}}
function dispose(){for(const chart of Object.values(charts))chart.dispose();for(const k of Object.keys(charts))delete charts[k]}
function resize(){for(const chart of Object.values(charts))chart.resize()}
async function load(){if(loading.value||stopped)return;loading.value=true;error.value='';const chosen=period.value;try{const result=(await api.get('/admin/dashboard',{params:{period:chosen}})).data.data;if(!stopped&&chosen===period.value){data.value=result;try{const p=(await api.get('/admin/providers',{params:{page_size:100}})).data.data.items;if(!stopped&&chosen===period.value)providerMetadata.value=Object.fromEntries(p.map((x:any)=>[x.id,x]))}catch{providerMetadata.value={}}}}catch(e){if(!stopped){error.value=message(e);data.value=null}}finally{loading.value=false;if(!stopped&&chosen!==period.value)void load()}}
async function render(){await nextTick();dispose();if(!data.value||stopped)return;const d=data.value,colors=['#2872dc','#19a891','#e7a53b','#d96363'];
for(const spec of specs){if(!hosts[spec.id])continue;const chart=echarts.init(hosts[spec.id]);charts[spec.id]=chart;
if(spec.id==='provider'||spec.id==='model'){const rows=d.rankings[spec.id];chart.setOption({color:colors,grid:{left:150,right:25,top:12,bottom:35},tooltip:{trigger:'axis'},xAxis:{type:'value'},yAxis:{type:'category',inverse:true,data:rows.map((r:any)=>r.label),axisLabel:{width:130,overflow:'truncate'}},series:[{type:'bar',data:rows.map((r:any)=>r.total_tokens),barMaxWidth:22}],graphic:rows.length?[]:[{type:'text',left:'center',top:'middle',style:{text:'暂无推理记录',fill:'#73849b'}}]});chart.on('click',(event:any)=>{const row=rows[event.dataIndex];if(event.componentType!=='series'||!row||row.other)return;if(spec.id==='provider'&&row.provider_id)void router.push('/admin/providers/'+row.provider_id);if(spec.id==='model'&&row.dimension)void router.push(usage({model:row.dimension}))});chart.setOption(chartTheme());continue}
const rows=spec.id==='concurrency'?d.concurrency_series:d.series;
const fields=spec.id==='tokens'?[['input_tokens','输入'],['output_tokens','输出'],['cached_tokens','缓存'],['total_tokens','总 Token']]:spec.id==='requests'?[['requests','全部请求'],['success','成功'],['failure','失败 / 取消']]:spec.id==='failures'?[['failure','失败 / 取消']]:[['active','执行'],['streaming','流式'],['queued','队列']];
chart.setOption({color:colors,grid:{left:52,right:20,top:50,bottom:50},legend:{top:5},tooltip:{trigger:'axis'},xAxis:{type:'category',data:rows.map((r:any)=>formatDate(r.bucket)),axisLabel:{hideOverlap:true}},yAxis:{type:'value',minInterval:spec.id==='tokens'?undefined:1},series:fields.map(([field,label])=>({name:label,type:'line',connectNulls:false,symbolSize:7,data:rows.map((r:any)=>r[field])})),graphic:(spec.id==='concurrency'?rows.some((r:any)=>r.samples>0):rows.length)?[]:[{type:'text',left:'center',top:'middle',style:{text:spec.id==='concurrency'?(d.history_available?'暂无历史采样':'采样状态不可用'):'暂无推理记录',fill:'#73849b'}}]});chart.setOption(chartTheme());chart.on('click',(event:any)=>{if(event.componentType!=='series'||spec.id==='concurrency')return;const row=rows[event.dataIndex];if(!row)return;const bucket=new Date(row.bucket).getTime(),size=d.grain==='hour'?3600000:86400000;const query={start:new Date(Math.max(bucket,new Date(d.start).getTime())).toISOString(),end:new Date(Math.min(bucket+size,new Date(d.end).getTime())).toISOString(),...(spec.id==='failures'||event.seriesName==='失败 / 取消'?{status:'failed'}:{})};void router.push({path:spec.id==='tokens'?'/admin/usage':'/admin/call-logs',query})})}}
watch(dark,render);watch(data,render);watch(period,load)
onMounted(()=>{void load();window.addEventListener('resize',resize);timer=setInterval(()=>{if(auto.value&&!document.hidden)void load()},15000)})
const observer=new ResizeObserver(resize)
watch(()=>data.value,async()=>{await nextTick();const main=document.querySelector('.workspace main');if(main)observer.observe(main)})
onBeforeUnmount(()=>{observer.disconnect();stopped=true;if(timer)clearInterval(timer);window.removeEventListener('resize',resize);dispose()})
</script>
<template><div v-loading="loading"><div class="dash-heading"><div><PageHeader title="概览 Dashboard" :description="'运行状态与资源用量 · '+branding.timezone"/></div><div class="dash-controls"><el-select v-model="period" aria-label="统计时段" style="width:140px"><el-option label="最近 1 小时" value="1h"/><el-option label="最近 24 小时" value="24h"/><el-option label="最近 7 天" value="7d"/><el-option label="最近 30 天" value="30d"/></el-select><el-checkbox v-model="auto">15 秒刷新</el-checkbox><el-button @click="load">刷新</el-button></div></div><el-alert v-if="error" :title="error" type="error" :closable="false"/>
<template v-if="data"><p class="muted">统计截至 {{formatDate(data.end)}} · 当前状态 {{data.live.timestamp?formatDate(data.live.timestamp):'不可用'}} <router-link :to="usage()" class="dash-link">查看完整用量 →</router-link></p><el-alert v-if="!data.live.available" title="Redis 状态不可用；当前并发、流式、队列和对象负载保持未知。" type="warning" :closable="false"/><div class="dash-kpis"><component :is="card.failed?'router-link':'div'" v-for="card in cards" :key="card.label" :to="card.failed?failed():undefined" class="dash-kpi" :class="{clickable:card.failed}"><span>{{card.label}}</span><strong>{{number(card.value)}}</strong><small v-if="card.failed">查看失败日志 →</small></component></div>
<div class="panel gateway-meter"><div><h2>网关并发</h2><strong>{{number(data.live.active)}} <span class="muted">/ {{number(data.live.max_concurrency)}}</span></strong></div><div class="meter-bar"><el-progress v-if="data.live.available" :percentage="Math.min(100,Math.round(data.live.active/data.live.max_concurrency*100))" :status="data.live.active/data.live.max_concurrency>=.8?'warning':undefined"/><p class="muted">其中流式 {{number(data.live.streaming)}} · 执行请求 / 当前配置上限 · 队列 {{number(data.live.queued)}} / {{number(data.live.queue_size)}}</p></div></div><p class="muted">今日从北京时间 00:00 起计；{{data.today.usage_unavailable}} 个今日请求的 Token 字段不完整；缺失字段未估算。{{data.concurrency_note}}</p>
<div class="dash-charts"><section v-for="spec in specs" :key="spec.id" class="panel"><h2>{{spec.title}}</h2><div :ref="el=>bindChart(spec.id,el)" class="dash-chart"></div></section></div>
<div class="dash-resources"><section class="panel"><div class="dash-heading"><h2>Provider 状态</h2><router-link to="/admin/providers" class="dash-link">模型供应商 →</router-link></div><p class="muted">显示 {{data.providers.length}} / {{data.provider_total}} 个账号；健康状态尚未验证不等于健康。失败率仅在所选时段排行有该账号记录时展示；最近延迟来自连接测试。</p><el-table :data="data.providers" empty-text="暂无 Provider，请在模型供应商配置"><el-table-column label="Provider" min-width="150"><template #default="s"><router-link :to="'/admin/providers/'+s.row.id" class="dash-link">{{s.row.name}}</router-link></template></el-table-column><el-table-column label="供应商" min-width="110"><template #default="s">{{providerMetadata[s.row.id]?.provider_type||'—'}}</template></el-table-column><el-table-column label="健康 / 调度" min-width="125"><template #default="s"><el-tag :type="s.row.health_status==='healthy'?'success':s.row.health_status==='unhealthy'?'danger':'info'">{{health[s.row.health_status]||s.row.health_status}}</el-tag><div class="muted">{{schedule[s.row.scheduling_state]}}</div></template></el-table-column><el-table-column label="当前 / 上限" width="125"><template #default="s">{{number(s.row.current_concurrency)}} / {{s.row.max_concurrency}}<el-progress v-if="s.row.current_concurrency!==null" :percentage="Math.min(100,s.row.current_concurrency/s.row.max_concurrency*100)" :show-text="false" :stroke-width="4"/></template></el-table-column><el-table-column label="失败率" width="95"><template #default="s">{{providerFailure(s.row.id)}}</template></el-table-column><el-table-column label="最近延迟" width="115"><template #default="s">{{providerMetadata[s.row.id]?.last_latency_ms==null?'—':providerMetadata[s.row.id].last_latency_ms+' ms'}}</template></el-table-column><template #empty><EmptyState title="暂无 Provider，请在模型供应商配置" description="检查筛选条件、时间范围或相关配置后重试。"/></template></el-table></section><section class="panel"><div class="dash-heading"><h2>用户组状态</h2><router-link to="/admin/user-groups" class="dash-link">用户组 →</router-link></div><p class="muted">显示 {{data.groups.length}} / {{data.group_total}} 个用户组。</p><el-table :data="data.groups" empty-text="暂无用户组"><el-table-column label="用户组" min-width="150"><template #default="s"><router-link :to="usage({user_group_id:String(s.row.id)})" class="dash-link">{{s.row.name}}</router-link></template></el-table-column><el-table-column label="状态" width="85"><template #default="s">{{s.row.status==='enabled'?'启用':'禁用'}}</template></el-table-column><el-table-column label="当前 / 上限" width="125"><template #default="s">{{number(s.row.current_concurrency)}} / {{s.row.max_concurrency}}<el-progress v-if="s.row.current_concurrency!==null" :percentage="Math.min(100,s.row.current_concurrency/s.row.max_concurrency*100)" :show-text="false" :stroke-width="4"/></template></el-table-column><template #empty><EmptyState title="暂无用户组" description="检查筛选条件、时间范围或相关配置后重试。"/></template></el-table></section></div>
</template></div></template>
<style scoped>.dash-heading{display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap}.dash-heading h1,.dash-heading h2{margin-bottom:8px}.dash-controls{display:flex;gap:14px;align-items:center;flex-wrap:wrap}.dash-kpis{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:14px;margin:24px 0}.dash-kpi{background:var(--surface);border:1px solid var(--line);border-radius:8px;padding:18px}.dash-kpi span{color:var(--muted);font-size:13px}.dash-kpi strong{display:block;font-size:28px;margin-top:10px}.dash-kpi small{color:var(--el-color-primary);display:block;margin-top:7px}.clickable:hover{border-color:var(--el-color-primary)}.gateway-meter{display:flex;align-items:center;gap:36px}.gateway-meter strong{font-size:28px}.meter-bar{flex:1}.dash-charts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.dash-resources{display:grid;grid-template-columns:1fr;gap:20px}.dash-charts .panel,.dash-resources .panel{margin-top:0;min-width:0}.dash-chart{height:280px;width:100%}.dash-resources{margin-top:20px}.dash-link{color:var(--el-color-primary)}@media(max-width:1000px){.dash-kpis{grid-template-columns:repeat(3,minmax(0,1fr))}.dash-charts,.dash-resources{grid-template-columns:1fr}}@media(max-width:700px){.dash-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}.gateway-meter{display:block}}
</style>
