<script setup lang="ts">
import {onMounted,reactive,ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api,message} from '../api/client'
import {formatDate} from '../ui/branding'
type Group={id:number,name:string,description:string,status:string,is_default:boolean,model_access:'all'|'selected',quota_limit:number,quota_period:string,max_concurrency:number,key_max_concurrency:number,model_group_ids:number[],created_at:string}
const rows=ref<Group[]>([]),options=ref<{id:number,name:string,status:string}[]>([]),page=ref(1),total=ref(0),q=ref(''),status=ref(''),loading=ref(false),saving=ref(false),error=ref(''),dialog=ref(false),editing=ref<number|null>(null)
const toggling=ref<number[]>([]),quotaValue=ref(0),quotaUnit=ref(10000)
const units=[{label:'Token',value:1},{label:'万',value:10000},{label:'百万',value:1000000},{label:'千万',value:10000000},{label:'亿',value:100000000},{label:'百亿',value:10000000000},{label:'万亿',value:1000000000000}]
const blank=()=>({name:'',description:'',status:'enabled',is_default:false,model_access:'all' as 'all'|'selected',quota_limit:0,quota_period:'monthly',max_concurrency:0,key_max_concurrency:0,model_group_ids:[] as number[]})
const form=reactive(blank())
async function load(){loading.value=true;error.value='';try{const d=(await api.get('/admin/user-groups',{params:{page:page.value,q:q.value,status:status.value}})).data.data;rows.value=d.items;total.value=d.total;options.value=(await api.get('/admin/model-group-options')).data.data}catch(e){error.value=message(e)}finally{loading.value=false}}
function open(g?:Group){editing.value=g?.id??null;Object.assign(form,blank(),g?{...g,model_group_ids:[...g.model_group_ids]}:{});quotaValue.value=g?.quota_limit??0;quotaUnit.value=g?1:10000;dialog.value=true}
function accessChanged(){form.model_access=form.model_group_ids.length?'selected':'all'}
function payload(g:typeof form|Group){return {name:g.name,description:g.description,status:g.status,quota_limit:g.quota_limit,quota_period:g.quota_period,max_concurrency:g.max_concurrency,key_max_concurrency:g.key_max_concurrency,model_group_ids:g.model_group_ids,model_access:g.model_access}}
async function save(){if(saving.value)return;const limit=quotaValue.value*quotaUnit.value;if(!form.name.trim()||!Number.isSafeInteger(limit)||limit<0){ElMessage.error('请填写名称及可精确表示的整数Token配额');return}form.name=form.name.trim();form.quota_limit=limit;saving.value=true;try{if(editing.value)await api.put('/admin/user-groups/'+editing.value,payload(form));else await api.post('/admin/user-groups',payload(form));dialog.value=false;ElMessage.success('用户组已保存');await load()}catch(e){ElMessage.error(message(e))}finally{saving.value=false}}
async function toggle(g:Group,value:boolean){if(toggling.value.includes(g.id)||g.is_default)return;toggling.value.push(g.id);try{await api.put('/admin/user-groups/'+g.id,{...payload(g),status:value?'enabled':'disabled'});await load()}catch(e){ElMessage.error(message(e))}finally{toggling.value=toggling.value.filter(id=>id!==g.id)}}
async function remove(g:Group){try{await ElMessageBox.confirm('删除后无法恢复，被用户引用的用户组不可删除。','删除 '+g.name,{type:'warning',confirmButtonText:'删除',cancelButtonText:'取消'});await api.delete('/admin/user-groups/'+g.id);await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(message(e))}}
onMounted(load)
</script>
<template><section class="panel groups-page">
<el-alert v-if="error" :title="error" type="error" :closable="false"/>
<div class="toolbar"><el-button type="primary" @click="open()">添加用户组</el-button><el-select v-model="status" placeholder="全部状态" clearable style="width:160px" @change="page=1;load()"><el-option label="启用" value="enabled"/><el-option label="禁用" value="disabled"/></el-select><el-input v-model="q" placeholder="搜索名称" style="width:240px" clearable @keyup.enter="page=1;load()"/><el-button :loading="loading" @click="page=1;load()">刷新</el-button></div>
<el-table :data="rows" v-loading="loading"><el-table-column label="名称" min-width="180"><template #default="s">{{s.row.name}} <el-tag v-if="s.row.is_default" size="small">默认</el-tag></template></el-table-column><el-table-column label="状态" width="100"><template #default="s">{{s.row.status==='enabled'?'启用':'禁用'}}</template></el-table-column><el-table-column label="组最大并发" min-width="120"><template #default="s">{{s.row.max_concurrency||'不限'}}</template></el-table-column><el-table-column label="单 API Key 最大并发" min-width="180"><template #default="s">{{s.row.key_max_concurrency||'不限'}}</template></el-table-column><el-table-column label="Token 配额" min-width="150"><template #default="s">{{s.row.quota_limit?s.row.quota_limit.toLocaleString():'不限'}}</template></el-table-column><el-table-column label="授权模型组" min-width="180"><template #default="s"><span v-if="s.row.model_access==='all'">不限</span><div v-else-if="s.row.model_group_ids.length" class="model-tags"><el-tag v-for="id in s.row.model_group_ids" :key="id" size="small">{{options.find(o=>o.id===id)?.name||('#'+id)}}</el-tag></div><span v-else>无授权（旧配置）</span></template></el-table-column><el-table-column prop="description" label="备注" min-width="180"/><el-table-column label="创建时间" min-width="170"><template #default="s">{{formatDate(s.row.created_at)}}</template></el-table-column><el-table-column label="操作" width="190" fixed="right"><template #default="s"><el-switch :model-value="s.row.status==='enabled'" :disabled="s.row.is_default||loading||toggling.includes(s.row.id)" :loading="toggling.includes(s.row.id)" :aria-label="'启用 '+s.row.name" @change="toggle(s.row,Boolean($event))"/><el-button link type="primary" @click="open(s.row)">编辑</el-button><el-button v-if="!s.row.is_default" link type="danger" @click="remove(s.row)">删除</el-button></template></el-table-column></el-table>
<el-pagination v-model:current-page="page" :total="total" :page-size="20" layout="total, prev, pager, next" @current-change="load"/>
</section>
<el-drawer v-model="dialog" :title="editing?'编辑用户组':'添加用户组'" size="560px"><el-form label-position="top" @submit.prevent="save"><el-form-item label="名称" required><el-input v-model="form.name" maxlength="80"/></el-form-item><el-form-item label="组最大并发"><el-input-number v-model="form.max_concurrency" :min="0" :max="100000" :precision="0"/><p class="muted field-note">0 表示不额外限制，继承网关有效并发上限</p></el-form-item><el-form-item label="单 API Key 最大并发"><el-input-number v-model="form.key_max_concurrency" :min="0" :max="100000" :precision="0"/><p class="muted field-note">0 表示不额外限制，继承用户组有效并发上限</p></el-form-item><el-form-item label="Token 配额"><div class="quota-input"><el-input-number v-model="quotaValue" :min="0" :max="9007199254740991/quotaUnit"/><el-select v-model="quotaUnit"><el-option v-for="u in units" :key="u.value" :label="u.label" :value="u.value"/></el-select></div><p class="muted field-note">0 表示不限</p></el-form-item><el-form-item label="授权模型组"><el-select v-model="form.model_group_ids" multiple filterable style="width:100%" placeholder="请选择" @change="accessChanged"><el-option v-for="o in options" :key="o.id" :label="o.name" :value="o.id"/></el-select><p class="muted field-note">未选择任何模型组时，该用户组可以访问全部模型。</p><div v-if="form.model_access==='selected'&&!form.model_group_ids.length" class="legacy-access"><el-alert title="当前旧配置没有授权模型；直接保存仍保留此权限。" type="warning" :closable="false"/><el-button link type="primary" @click="form.model_access='all'">改为允许全部模型</el-button></div></el-form-item><el-form-item label="状态"><el-switch v-model="form.status" active-value="enabled" inactive-value="disabled" :disabled="form.is_default"/></el-form-item><el-form-item label="备注"><el-input v-model="form.description" type="textarea" :maxlength="editing?2000:255" show-word-limit/></el-form-item><el-form-item v-if="editing" label="配额周期"><el-select v-model="form.quota_period"><el-option label="每日" value="daily"/><el-option label="每月" value="monthly"/><el-option label="永久" value="permanent"/></el-select></el-form-item></el-form><template #footer><el-button :disabled="saving" @click="dialog=false">取消</el-button><el-button type="primary" :disabled="!form.name.trim()" :loading="saving" @click="save">保存</el-button></template></el-drawer>
</template>
<style scoped>.groups-page{margin:0;min-height:calc(100vh - 82px)}.toolbar{gap:12px}.model-tags{display:flex;flex-wrap:wrap;gap:4px}.el-switch{margin-right:12px}.el-pagination{margin-top:20px}.field-note{width:100%;font-size:12px;margin:8px 0 0}.quota-input{display:flex;gap:10px;width:100%}.quota-input .el-select{width:120px}.legacy-access{width:100%;margin-top:10px}</style>
