<script setup lang="ts">
import {computed,onMounted,onBeforeUnmount,reactive,ref,watch} from 'vue'
import {onBeforeRouteLeave} from 'vue-router'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api,message} from '../api/client'
import {loadBranding,formatDate} from '../ui/branding'
import SystemStatus from '../components/SystemStatus.vue'
import {settingsTabs,settingsPayload,acceptSaved,copy,equal} from '../ui/settingsDraft'
const form=reactive<any>({}),ready=ref(false),loading=ref(false),saving=ref(false),error=ref(''),tab=ref('brand'),rules=ref('')
const vectorOptions=ref<any[]>([]),configs=ref<any[]>([]),groups=ref<any[]>([]),routeId=ref<number|null>(null),routeSaving=ref(false),testLoading=ref(false),esStatus=ref<any>({}),vectorResult=ref<any>(null)
const routeBlank=()=>({virtual_model:'AI-Auto',embedding_model:'',simple_model_group:null,complex_model_group:null,similarity_threshold:.75,confidence_gap:.1,top_k:5,fallback:'simple',status:'disabled'})
const routeForm=reactive<any>(routeBlank())
const baseline=ref<any>(null),routeBaseline=ref<any>(null)
const routeSelection=ref<number|null>(null)
const routeValues=()=>Object.fromEntries(Object.keys(routeBlank()).map(key=>[key,routeForm[key]]))
const routeDirty=computed(()=>!!routeBaseline.value&&!equal(routeValues(),routeBaseline.value))
const dirtyTabs=computed(()=>baseline.value?Object.keys(settingsTabs).filter(key=>!equal(settingsPayload(form,rules.value,key),settingsPayload(baseline.value,baseline.value.logging.redaction_rules.join('\n'),key))):[])
const currentDirty=computed(()=>dirtyTabs.value.includes(tab.value))
const pending=computed(()=>dirtyTabs.value.length>0||routeDirty.value)
async function confirmDiscard(){try{await ElMessageBox.confirm('有尚未保存的更改，继续将放弃这些更改。','未保存更改',{confirmButtonText:'放弃更改',cancelButtonText:'继续编辑',type:'warning'});return true}catch{return false}}
async function reload(){if(pending.value&&!await confirmDiscard())return;await load()}
function resetCurrent(){const fields=settingsPayload(baseline.value,baseline.value.logging.redaction_rules.join('\n'),tab.value);if(tab.value==='brand')fields.basic={...fields.basic,logo:baseline.value.basic.logo,icon:baseline.value.basic.icon};for(const [section,values] of Object.entries(fields))for(const key of Object.keys(values))form[section][key]=copy(baseline.value[section][key]);if(tab.value==='basic')rules.value=baseline.value.logging.redaction_rules.join('\n')}
function beforeUnload(event:BeforeUnloadEvent){if(pending.value){event.preventDefault();event.returnValue=''}}
onBeforeRouteLeave(async()=>saving.value||routeSaving.value?false:!pending.value||await confirmDiscard())
const requests=new Set<AbortController>()
const auxiliaryReady=reactive<Record<string,boolean>>({})
const auxiliaryLoading=reactive<Record<string,boolean>>({})
const auxiliaryError=reactive<Record<string,string>>({})
let disposed=false,generation=0
onBeforeUnmount(()=>{disposed=true;generation++;for(const request of requests)request.abort();window.removeEventListener('beforeunload',beforeUnload)})
const providers=computed(()=>[...new Map(vectorOptions.value.map(o=>[o.provider_id,{id:o.provider_id,name:o.provider_name}])).values()])
const vectorModels=computed(()=>vectorOptions.value.filter(o=>o.provider_id===form.vector?.provider_id))
const gatewayFields=[['max_concurrency','最大并发','同时执行的请求数量上限',1,100000],['queue_size','队列大小','达到并发上限时允许等待的请求数量',0,100000],['queue_timeout','队列等待超时（秒）','超过等待时间后返回超时',1,3600],['nonstream_timeout','非流式请求超时（秒）','非流式调用及上游响应头等待上限',1,600],['stream_idle_timeout','流式空闲超时（秒）','连续无数据返回时关闭流式连接',1,3600],['max_body_bytes','最大请求体（字节）','超过上限的请求会被拒绝，最高 10 MiB',1024,10485760]] as const
function selectRoute(){const current=configs.value.find(c=>c.id===routeId.value);Object.assign(routeForm,routeBlank(),current||{});if(!current)routeForm.embedding_model=savedVector.value.model||'';routeBaseline.value=copy(routeValues());routeSelection.value=routeId.value}
async function changeRoute(next:number|null){if(routeDirty.value){try{await ElMessageBox.confirm('切换规则将放弃当前规则中尚未保存的更改。','切换路由规则',{confirmButtonText:'放弃并切换',cancelButtonText:'继续编辑',type:'warning'})}catch{routeId.value=routeSelection.value;return}}routeId.value=next;selectRoute()}
async function load(){
  if(loading.value)return
  const version=++generation,request=new AbortController();requests.add(request)
  for(const previous of requests)if(previous!==request)previous.abort()
  for(const key of ['vector','smart','elasticsearch']){auxiliaryReady[key]=false;auxiliaryLoading[key]=false;auxiliaryError[key]=''}
  loading.value=true;error.value=''
  try{
    const s=await api.get('/admin/settings',{params:{include_assets:false},signal:request.signal,timeout:15000})
    if(disposed||version!==generation)return
    Object.assign(form,s.data.data);baseline.value=copy(s.data.data);savedVector.value=copy(form.vector);rules.value=form.logging.redaction_rules.join('\n')
    routeBaseline.value=null;ready.value=true;vectorResult.value=null
  }catch(e){if(!request.signal.aborted)error.value=message(e)}finally{requests.delete(request);if(version===generation){loading.value=false;if(!error.value&&ready.value)void loadAuxiliary(tab.value)}}
}
async function loadAuxiliary(key:string,force=false){
  if(!ready.value||loading.value||disposed||!['vector','smart','elasticsearch'].includes(key)||auxiliaryLoading[key]||auxiliaryReady[key]&&!force)return
  const version=generation,request=new AbortController();requests.add(request);auxiliaryLoading[key]=true;auxiliaryError[key]='';if(key==='elasticsearch'&&!auxiliaryReady[key])esStatus.value={unavailable:true}
  const options={signal:request.signal,timeout:15000}
  try{
    if(key==='vector'){
      const v=await api.get('/admin/settings/vector-options',options)
      if(disposed||version!==generation)return
      vectorOptions.value=v.data.data
    }else if(key==='smart'){
      const [c,g]=await Promise.all([api.get('/admin/smart-route/configs',options),api.get('/admin/model-group-options',options)])
      if(disposed||version!==generation)return
      configs.value=c.data.data;groups.value=g.data.data
      if(routeId.value&&!configs.value.some(c=>c.id===routeId.value))routeId.value=null
      if(!routeId.value&&configs.value.length)routeId.value=configs.value[0].id
      if(!routeDirty.value)selectRoute()
    }else{
      const s=await api.get('/admin/settings/elasticsearch/status',options)
      if(disposed||version!==generation)return
      esStatus.value=s.data.data
    }
    auxiliaryReady[key]=true
  }catch(e){if(!request.signal.aborted&&version===generation){auxiliaryError[key]=message(e);if(key==='elasticsearch')esStatus.value={unavailable:true}}}finally{requests.delete(request);if(version===generation)auxiliaryLoading[key]=false}
}
async function loadEsStatus(){await loadAuxiliary('elasticsearch',true)}
watch(tab,key=>void loadAuxiliary(key))
async function save(){
  if(saving.value||routeSaving.value||!currentDirty.value)return
  const savingTab=tab.value,sent=copy(settingsPayload(form,rules.value,savingTab)),sentRules=rules.value
  if(savingTab==='basic'){const address=sent.basic.public_api_base_url.trim();if(address&&!address.replace(/\/$/,'').endsWith('/v1')){ElMessage.error('接入地址须以 /v1 结尾');return}form.basic.public_api_base_url=sent.basic.public_api_base_url=address}
  saving.value=true
  try{
    if(savingTab==='vector')await ElMessageBox.confirm('更换共享向量服务会使已有路由和审核样本向量失效。保存后需手动重建，重建可能产生用量和费用。','保存向量服务',{confirmButtonText:'保存',cancelButtonText:'取消'})
    const saved=(await api.patch('/admin/settings',{revision:form.revision,...sent},{params:{include_assets:false}})).data.data
    acceptSaved(form,baseline.value,sent,saved)
    if(savingTab==='basic'&&rules.value===sentRules)rules.value=saved.logging.redaction_rules.join('\n')
    if(savingTab==='vector'){savedVector.value=copy(saved.vector);vectorResult.value=null}
    ElMessage.success(settingsTabs[savingTab]+'已保存')
    // Auxiliary refresh failure must not report an already committed save as failed.
    if(savingTab==='brand'||savingTab==='basic')try{await loadBranding()}catch{ElMessage.warning('配置已保存，品牌显示请刷新页面更新')}
    if(savingTab==='vector')try{configs.value=(await api.get('/admin/smart-route/configs')).data.data;if(!routeDirty.value)selectRoute()}catch{ElMessage.warning('配置已保存，路由列表暂时无法刷新')}
    if(savingTab==='elasticsearch')void loadEsStatus()
  }catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(message(e))}finally{saving.value=false}
}
const savedVector=ref<any>({})
async function saveRoute(){if(routeSaving.value||saving.value)return;routeSaving.value=true;const sent=copy(routeValues());try{const body={...sent,embedding_model:savedVector.value.model||sent.embedding_model};const endpoint='/admin/smart-route/configs'+(routeId.value?'/'+routeId.value:'');const d=(await api[routeId.value?'put':'post'](endpoint,body)).data.data;routeId.value=routeSelection.value=d.id;for(const key of Object.keys(sent))if(equal(routeForm[key],sent[key]))routeForm[key]=d[key];routeBaseline.value=Object.fromEntries(Object.keys(routeBlank()).map(key=>[key,d[key]]));ElMessage.success('路由规则已保存');try{configs.value=(await api.get('/admin/smart-route/configs')).data.data}catch{ElMessage.warning('规则已保存，列表暂时无法刷新')}}catch(e){ElMessage.error(message(e))}finally{routeSaving.value=false}}
async function testVector(){try{await ElMessageBox.confirm('使用已保存的账号和模型发起一次短文本向量调用，可能产生费用。','测试向量服务',{confirmButtonText:'测试',cancelButtonText:'取消'});testLoading.value=true;vectorResult.value=(await api.post('/admin/settings/vector-test',{consent:true,revision:form.revision})).data.data;ElMessage.success('向量服务可用')}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(message(e))}finally{testLoading.value=false}}
async function testEs(){testLoading.value=true;try{const d=(await api.post('/admin/settings/elasticsearch/test')).data.data;ElMessage.success('连接成功，Elasticsearch '+d.version);await loadEsStatus()}catch(e){ElMessage.error(message(e))}finally{testLoading.value=false}}
function image(event:Event,key:'logo'|'icon'){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;if(file.type!=='image/png'||file.size>256*1024){ElMessage.error('请选择不超过256KiB的PNG图片');return}const reader=new FileReader();reader.onload=()=>{form.basic[key]=String(reader.result)};reader.readAsDataURL(file)}
onMounted(async()=>{window.addEventListener('beforeunload',beforeUnload);await load()})
</script>
<template>
<PageHeader title="系统设置"><el-button v-if="tab!=='status'" :disabled="saving||routeSaving||testLoading" :loading="loading" @click="reload">重新加载</el-button></PageHeader>
<el-alert v-if="error" :title="error" type="error" :closable="false"/>
<el-skeleton v-if="!ready&&loading" :rows="8" animated/>
<section v-if="ready" class="panel settings-panel" v-loading="loading"><el-alert v-if="auxiliaryError[tab]" :title="auxiliaryError[tab]" type="error" :closable="false"><el-button link type="primary" @click="loadAuxiliary(tab,true)">重新加载当前页签</el-button></el-alert><el-tabs v-model="tab" :before-leave="()=>!saving&&!routeSaving">
<el-tab-pane label="基础与品牌" name="brand" lazy><el-form label-position="top"><el-form-item label="系统名称"><el-input v-model="form.basic.system_name" maxlength="80"/></el-form-item><div class="settings-grid"><el-form-item v-for="key in (['logo','icon'] as const)" :key="key" :label="key==='logo'?'系统Logo':'浏览器Icon'"><img v-if="form.basic[key]" :src="form.basic[key]" class="brand-preview"/><input type="file" accept="image/png" @change="image($event,key)"/><el-button text @click="form.basic[key]=''">清除</el-button></el-form-item></div><el-form-item label="系统URL"><el-input v-model="form.basic.system_url" placeholder="留空使用当前网站地址"/></el-form-item><el-form-item label="语言"><el-select v-model="form.basic.language"><el-option label="简体中文" value="zh-CN"/></el-select></el-form-item><el-form-item label="显示时区"><el-input v-model="form.basic.timezone" placeholder="Asia/Shanghai、UTC或有效IANA时区"/></el-form-item><p class="muted">显示时间使用此时区；Token配额周期与统计分桶仍按北京时间计算。</p></el-form></el-tab-pane>
<el-tab-pane label="基础设置" name="basic" lazy><div class="section-heading"><h2>基础设置</h2><p>管理对外接入地址、调用日志留存和协议适配。</p></div><el-form label-position="top" class="settings-form"><el-form-item label="接入地址（OpenAI Base URL）"><el-input v-model="form.basic.public_api_base_url" placeholder="http://网关地址:端口/v1"/><p class="field-hint">支持 HTTP / HTTPS，以 /v1 结尾；留空使用当前站点地址 /v1。</p></el-form-item><el-form-item label="日志保留天数"><el-input-number v-model="form.logging.retention_days" :min="1" :max="3650" :precision="0"/><p class="field-hint">调用、决策与审核日志到期分批清理；用量汇总和管理审计长期保留。已有 366 天及以上配置继续兼容。</p></el-form-item><div class="setting-line"><div><strong>协议转换</strong><p>优先原生协议；开启后允许 Chat Completions 与 Anthropic Messages 相互转换。</p></div><el-switch v-model="form.gateway.protocol_conversion" aria-label="协议转换"/></div><p class="field-hint">协议专属字段、工具和多模态内容可能无法安全转换；Responses 使用原生协议。</p><el-divider/><h3>正文与脱敏</h3><div class="setting-line"><div><strong>保存请求正文</strong><p>仅保存脱敏预览，最多 16 KiB。</p></div><el-switch v-model="form.logging.save_request_body" aria-label="保存请求正文"/></div><div class="setting-line"><div><strong>保存响应正文</strong><p>流式响应保存有限事件预览。</p></div><el-switch v-model="form.logging.save_response_body" aria-label="保存响应正文"/></div><el-form-item label="附加脱敏正则"><el-input v-model="rules" type="textarea" :rows="4" placeholder="每行一条，最多 20 条"/></el-form-item><p class="field-hint">认证头不保存，密码与密钥字段始终脱敏。开启正文记录后会保存客户输入和模型输出。</p></el-form></el-tab-pane>
<el-tab-pane label="性能设置" name="performance" lazy><div class="section-heading"><h2>性能设置</h2><p>限制并发、队列和超时，控制网关资源占用。</p></div><el-form label-position="top" class="settings-form settings-grid"><el-form-item v-for="[key,label,hint,min,max] in gatewayFields" :key="key" :label="label"><el-input-number v-model="form.gateway[key]" :min="min" :max="max" :precision="0"/><p class="field-hint">{{hint}}</p></el-form-item></el-form><el-collapse class="settings-form"><el-collapse-item title="高级调度参数" name="advanced"><el-form label-position="top" class="settings-grid"><el-form-item label="会话粘性（秒）"><el-input-number v-model="form.gateway.sticky_timeout" :min="1" :max="86400"/></el-form-item><el-form-item label="模型列表巡检间隔（秒）"><el-input-number v-model="form.gateway.health_check_interval" :min="0" :max="86400"/><p class="field-hint">0 表示关闭，巡检不会发起生成请求。</p></el-form-item><el-form-item label="普通故障阈值"><el-input-number v-model="form.gateway.failure_threshold" :min="1" :max="100"/></el-form-item><el-form-item label="初始冷却时间（秒）"><el-input-number v-model="form.gateway.cooldown_seconds" :min="1" :max="3600"/></el-form-item></el-form></el-collapse-item></el-collapse><p class="field-hint">降低并发上限不会中断正在执行的请求。</p></el-tab-pane>
<el-tab-pane label="向量服务" name="vector" lazy><div class="section-heading"><h2>向量服务</h2><p>为智能路由和内容合规提供共享的语义向量能力。</p></div><el-form label-position="top" class="settings-form" v-loading="auxiliaryLoading.vector"><el-form-item label="向量账号"><el-select v-model="form.vector.provider_id" :disabled="!auxiliaryReady.vector" filterable placeholder="选择已启用的向量账号" @change="form.vector.model='';vectorResult=null"><el-option v-for="p in providers" :key="p.id" :label="p.name" :value="p.id"/></el-select></el-form-item><el-form-item label="向量模型"><el-select v-model="form.vector.model" filterable :disabled="!form.vector.provider_id||!auxiliaryReady.vector" placeholder="选择账号下已启用的向量模型" @change="vectorResult=null"><el-option v-for="m in vectorModels" :key="m.model" :label="m.model+' → '+m.upstream_model" :value="m.model"/></el-select></el-form-item><el-empty v-if="auxiliaryReady.vector&&!providers.length" description="暂无可用向量账号"><router-link to="/admin/providers"><el-button type="primary">配置模型供应商</el-button></router-link></el-empty><el-alert title="更换服务后需手动重建已有样本向量" type="info" :closable="false">所有路由规则将使用新向量模型。保存不会触发调用；未配置共享服务时保留各路由原配置和本地内容合规向量。</el-alert><div class="section-actions"><el-button :loading="testLoading" :disabled="!savedVector.model||saving" @click="testVector">测试已保存的连接</el-button><router-link to="/admin/smart-route/samples">管理路由样本</router-link><router-link to="/admin/compliance/samples">管理审核样本</router-link></div><p v-if="vectorResult" class="test-success">测试成功 · 向量维度 {{vectorResult.dimensions}} · <router-link :to="'/admin/call-logs/'+vectorResult.request_id">查看调用日志</router-link></p></el-form></el-tab-pane>
<el-tab-pane label="智能路由" name="smart" lazy><div class="section-heading"><h2>智能路由</h2><p>将请求分类到简单或复杂任务模型组。</p></div><div class="setting-line settings-form"><div><strong>智能路由总开关</strong><p>关闭后所有虚拟路由模型停止提供服务，规则与样本保留。</p></div><el-switch v-model="form.governance.smart_route_enabled" aria-label="智能路由总开关"/></div><el-divider/><el-skeleton v-if="auxiliaryLoading.smart" :rows="6" animated/><el-form v-if="auxiliaryReady.smart" label-position="top" class="settings-form"><div class="rule-selector"><el-select v-model="routeId" placeholder="选择路由规则" :disabled="routeSaving||saving" @change="changeRoute"><el-option v-for="c in configs" :key="c.id" :label="c.virtual_model" :value="c.id"/></el-select><el-button :disabled="routeSaving||saving" @click="changeRoute(null)">新建规则</el-button></div><div class="settings-grid"><el-form-item label="规则状态"><el-switch v-model="routeForm.status" active-value="enabled" inactive-value="disabled"/></el-form-item><el-form-item label="虚拟模型名称"><el-input v-model="routeForm.virtual_model" :disabled="!!routeId" maxlength="100"/></el-form-item><el-form-item label="简单请求模型组"><el-select v-model="routeForm.simple_model_group" filterable placeholder="选择已启用的模型组"><el-option v-for="g in groups.filter(x=>x.status==='enabled')" :key="g.id" :value="g.id" :label="g.name"/></el-select></el-form-item><el-form-item label="复杂请求模型组"><el-select v-model="routeForm.complex_model_group" filterable placeholder="选择已启用的模型组"><el-option v-for="g in groups.filter(x=>x.status==='enabled')" :key="g.id" :value="g.id" :label="g.name"/></el-select></el-form-item><el-form-item label="分类阈值"><el-input-number v-model="routeForm.similarity_threshold" :min="0" :max="1" :step=".01" :precision="2"/></el-form-item><el-form-item label="置信度差距值"><el-input-number v-model="routeForm.confidence_gap" :min="0" :max="1" :step=".01" :precision="2"/></el-form-item><el-form-item label="Top K"><el-input-number v-model="routeForm.top_k" :min="1" :max="50" :precision="0"/></el-form-item><el-form-item label="向量模型"><el-input :model-value="savedVector.model||routeForm.embedding_model" disabled/><p class="field-hint">新规则需先保存向量服务配置。</p></el-form-item><el-form-item label="向量调用失败时"><el-select v-model="routeForm.fallback"><el-option value="simple" label="使用简单请求模型组"/><el-option value="complex" label="使用复杂请求模型组"/><el-option value="error" label="返回错误"/></el-select></el-form-item></div><p class="field-hint">未达到分类阈值或置信度差距不足时按简单请求处理。目标模型组须不同，并包含可用的文本模型。</p><div class="section-actions"><el-button type="primary" :loading="routeSaving" :disabled="saving||testLoading||!(savedVector.model||routeForm.embedding_model)||(!routeDirty&&!!routeId)" @click="saveRoute">保存路由规则</el-button><el-button :disabled="!routeDirty||saving||routeSaving" @click="selectRoute">撤销规则更改</el-button><span v-if="routeDirty" class="muted">规则有未保存更改</span><router-link to="/admin/smart-route/samples">管理分类样本</router-link></div></el-form></el-tab-pane>
<el-tab-pane label="内容合规" name="compliance" lazy><div class="section-heading"><h2>内容合规</h2><p>统一控制敏感词和语义样本审核。</p></div><el-form label-position="top" class="settings-form"><div class="setting-line"><div><strong>内容合规总开关</strong><p>开启后依据启用策略执行审核或阻断。</p></div><el-switch v-model="form.governance.compliance_enabled" aria-label="内容合规总开关"/></div><el-form-item label="语义阈值"><el-input-number v-model="form.governance.semantic_threshold" :min="0" :max="1" :step=".01" :precision="2"/><p class="field-hint">留空沿用各策略原有阈值；填写后作为全局阈值。数值越高，语义越接近才命中。</p></el-form-item><div class="section-actions"><router-link to="/admin/compliance/words">敏感词</router-link><router-link to="/admin/compliance/samples">审核样本</router-link><router-link to="/admin/compliance/policies">策略规则</router-link><router-link to="/admin/compliance/logs">审核日志</router-link></div></el-form></el-tab-pane>
<el-tab-pane label="Elasticsearch" name="elasticsearch" lazy><div class="section-heading"><h2>Elasticsearch</h2><p>将调用、管理审计日志及可选脱敏正文写入外部检索服务，支持 Elasticsearch 9.x。</p></div><div class="es-overview" v-loading="auxiliaryLoading.elasticsearch"><div><span>服务状态</span><strong>{{esStatus.unavailable?'状态不可用':esStatus.enabled?'已启用':esStatus.configured?'已配置，未启用':'未配置'}}</strong></div><div><span>当前队列</span><strong>{{esStatus.queue_count??'—'}} 条 / {{esStatus.queue_bytes??'—'}} 字节</strong></div><div><span>累计丢弃</span><strong>{{esStatus.dropped??'—'}}</strong></div><div><span>最近写入成功</span><strong>{{esStatus.last_success?formatDate(esStatus.last_success):'暂无'}}</strong></div><div><span>连续失败开始</span><strong>{{esStatus.failure_since?formatDate(esStatus.failure_since):'暂无'}}</strong></div></div><el-alert v-if="esStatus.last_error" :title="'最近错误：'+esStatus.last_error" type="warning" :closable="false"/><el-form label-position="top" class="settings-form"><div class="setting-line"><div><strong>启用外部日志</strong><p>关闭后停止写入，仅管理本应用专用日志索引。</p></div><el-switch v-model="form.elasticsearch.enabled" aria-label="启用 Elasticsearch"/></div><el-form-item label="Elasticsearch 地址"><el-input v-model="form.elasticsearch.url" placeholder="https://elasticsearch.example:9200"/></el-form-item><div class="settings-grid"><el-form-item label="认证方式"><el-select v-model="form.elasticsearch.auth_type"><el-option value="api_key" label="API Key"/><el-option value="basic" label="Basic Auth"/></el-select></el-form-item><el-form-item v-if="form.elasticsearch.auth_type==='basic'" label="用户名"><el-input v-model="form.elasticsearch.username" autocomplete="off"/></el-form-item></div><el-form-item :label="form.elasticsearch.auth_type==='basic'?'密码':'API Key'"><el-input v-model="form.elasticsearch.secret" type="password" show-password autocomplete="new-password" :placeholder="form.elasticsearch.secret_configured?'已加密保存，留空保留原值':'填写认证密钥'"/><p class="field-hint">变更地址或认证信息时须重新填写，已有密钥不会返回浏览器。</p></el-form-item><div class="settings-grid"><el-form-item label="请求正文上限（KiB）"><el-input-number v-model="form.elasticsearch.request_body_kib" :min="0" :max="16"/><p class="field-hint">0 表示不保存正文。</p></el-form-item><el-form-item label="响应正文上限（KiB）"><el-input-number v-model="form.elasticsearch.response_body_kib" :min="0" :max="16"/><p class="field-hint">正文始终脱敏，超出上限截断。</p></el-form-item><el-form-item label="外部保留天数"><el-input-number v-model="form.elasticsearch.retention_days" :min="1" :max="365"/></el-form-item></div><p class="field-hint">队列最多 1,000 条 / 8 MiB，满时丢弃新记录；失败保留重试。更换服务地址不会向新服务器发送旧队列数据。</p><div class="section-actions"><el-button :loading="testLoading" :disabled="saving" @click="testEs">测试已保存的连接</el-button><el-button @click="loadEsStatus">刷新状态</el-button></div></el-form></el-tab-pane>
<el-tab-pane label="系统状态" name="status" lazy><SystemStatus :active="tab==='status'"/></el-tab-pane>
</el-tabs><div v-if="tab!=='status'" class="settings-savebar" role="region" aria-label="当前页签保存"><div aria-live="polite"><strong>{{settingsTabs[tab]}}</strong><span :class="{'pending-change':currentDirty}">{{currentDirty?'有未保存更改':'配置已同步'}}</span><small v-if="dirtyTabs.filter(key=>key!==tab).length">其他 {{dirtyTabs.filter(key=>key!==tab).length}} 个页签有待保存更改</small><small>{{tab==='smart'?'此处仅保存总开关；路由规则在规则表单内保存。':'仅保存当前页签的配置。'}}</small></div><div class="settings-save-actions"><el-button :disabled="!currentDirty||saving||routeSaving||loading" @click="resetCurrent">撤销更改</el-button><el-button type="primary" :disabled="!currentDirty||loading||routeSaving||testLoading" :loading="saving" @click="save">{{tab==='smart'?'保存总开关':'保存'+settingsTabs[tab]}}</el-button></div></div></section></template>
<style scoped>
.settings-savebar{position:sticky;bottom:12px;z-index:20;display:flex;align-items:center;justify-content:space-between;gap:20px;margin-top:28px;padding:16px 20px;border:1px solid var(--el-border-color);border-radius:10px;background:var(--el-bg-color);box-shadow:0 4px 20px rgba(25,45,70,.08)}.settings-savebar strong{font-size:14px;margin-right:16px}.settings-savebar span{font-size:13px;color:var(--el-text-color-secondary)}.settings-savebar .pending-change{color:var(--el-color-warning)}.settings-savebar small{display:block;font-size:12px;color:var(--el-text-color-secondary);margin-top:6px}.settings-save-actions{display:flex;gap:12px;flex-shrink:0}.settings-save-actions :deep(.el-button+.el-button){margin-left:0}@media(max-width:700px){.settings-savebar{align-items:stretch;flex-direction:column;padding:14px;gap:12px;bottom:8px}.settings-save-actions{justify-content:flex-end;flex-wrap:wrap}}
.settings-panel{padding:8px 24px 28px}.section-heading{margin:20px 0 28px}.section-heading h2{font-size:18px;margin:0 0 8px}.field-hint{width:100%}.section-heading p,.field-hint{color:var(--el-text-color-secondary);font-size:13px;line-height:1.6;margin:8px 0 0}.settings-form{max-width:920px}.settings-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 32px}.settings-form :deep(.el-select){width:100%}.settings-form :deep(.el-input-number){width:210px}.setting-line{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:18px 0;border-bottom:1px solid var(--el-border-color-lighter);margin-bottom:20px}.setting-line p{color:var(--el-text-color-secondary);margin:6px 0 0;font-size:13px}.brand-preview{width:48px;height:48px;object-fit:contain;margin-right:16px}.section-actions{display:flex;align-items:center;gap:20px;flex-wrap:wrap;margin-top:24px}.section-actions a{color:var(--el-color-primary);font-size:14px}.rule-selector{display:flex;gap:12px;margin:0 0 24px}.es-overview{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px;padding:20px;background:var(--el-fill-color-light);border-radius:8px;margin-bottom:24px}.es-overview span{display:block;font-size:13px;color:var(--el-text-color-secondary);margin-bottom:8px}.es-overview strong{font-size:14px;font-weight:500}.test-success{color:var(--el-color-success)}@media(max-width:700px){.settings-grid,.es-overview{grid-template-columns:1fr}.settings-panel{padding:8px 16px 24px}}
</style>
