<script setup lang="ts">
import {branding,formatDate} from '../ui/branding'
import {computed,ref,watch,nextTick,onBeforeUnmount} from 'vue'
import * as echarts from 'echarts'
import {dark,chartTheme} from '../ui/preferences'
import {useRoute,useRouter} from 'vue-router'
import {api,message} from '../api/client'
const route=useRoute(),router=useRouter(),admin=computed(()=>route.path.startsWith('/admin/'))
const result=ref<any>(null),error=ref(''),loading=ref(false),range=ref<Date[]>([])
const filters=ref<Record<string,string>>({}),grain=ref('day');let generation=0
const advanced=ref(false)
const dimensions=computed(()=>admin.value?['user_id','user_group_id','api_key_id','provider_id','model','protocol','operation']:['api_key_id','model','operation'])
const labels:Record<string,string>={user_id:'用户 ID',user_group_id:'用户组 ID',api_key_id:'API Key ID',provider_id:'账号 ID',model:'逻辑模型',protocol:'协议',operation:'操作（chat/messages等）',requests:'请求数',success:'成功',failure:'失败 / 取消',failure_rate:'失败率 %',active_users:'活跃用户',input_tokens:'输入 Token',output_tokens:'输出 Token',cached_tokens:'缓存 Token',total_tokens:'总 Token',usage_unavailable:'Token 字段不完整',average_ttft_ms:'平均 TTFT · ms',average_tokens_per_second:'平均 Tokens/s'}
const chartHost=ref<HTMLElement>(),chartMetric=ref('total_tokens');let chart:echarts.ECharts|undefined
const chartMetrics=['total_tokens','requests','failure_rate','average_ttft_ms','average_tokens_per_second']
async function renderChart(){await nextTick();if(!chartHost.value||!result.value)return;chart?.dispose();chart=echarts.init(chartHost.value);const rows=result.value.series;chart.setOption({grid:{left:60,right:24,top:25,bottom:55},tooltip:{trigger:'axis'},xAxis:{type:'category',data:rows.map((r:any)=>formatDate(r.bucket))},yAxis:{type:'value',name:labels[chartMetric.value]},series:[{type:'line',smooth:.3,smoothMonotone:'x',showSymbol:rows.length<=2,connectNulls:false,data:rows.map((r:any)=>r[chartMetric.value]),symbolSize:5,lineStyle:{color:'#2872dc',width:2.5},itemStyle:{color:'#2872dc'}}],graphic:rows.length?[]:[{type:'text',left:'center',top:'middle',style:{text:'所选区间暂无推理请求',fill:'#73849b'}}]});chart.setOption(chartTheme());chart.on('click',(event:any)=>{if(!admin.value||event.componentType!=='series')return;const begin=new Date(rows[event.dataIndex].bucket).getTime(),duration=result.value.grain==='hour'?3600000:86400000;const query:Record<string,string>={start:new Date(Math.max(begin,new Date(result.value.start).getTime())).toISOString(),end:new Date(Math.min(begin+duration,new Date(result.value.end).getTime())).toISOString()};for(const k of dimensions.value)if(filters.value[k])query[k]=filters.value[k];void router.push({path:'/admin/call-logs',query})})}
function resizeChart(){chart?.resize()}
window.addEventListener('resize',resizeChart)
watch([result,chartMetric,dark],renderChart)
const observer=new ResizeObserver(resizeChart)
watch(()=>result.value,async()=>{await nextTick();const main=document.querySelector('.workspace main');if(main)observer.observe(main)})
onBeforeUnmount(()=>{observer.disconnect();generation++;chart?.dispose();window.removeEventListener('resize',resizeChart)})
const metrics=['total_tokens','input_tokens','output_tokens','cached_tokens','requests','failure_rate','average_ttft_ms','average_tokens_per_second']
async function load(){const mine=++generation;loading.value=true;error.value='';result.value=null;filters.value={};for(const k of dimensions.value)filters.value[k]=String(route.query[k]||'');if(dimensions.value.some(k=>route.query[k]))advanced.value=true;grain.value=String(route.query.grain||'day');range.value=route.query.start&&route.query.end?[new Date(String(route.query.start)),new Date(String(route.query.end))]:[];try{const data=(await api.get((admin.value?'/admin':'/portal')+'/usage',{params:route.query})).data.data;if(mine===generation)result.value=data}catch(e){if(mine===generation)error.value=message(e)}finally{if(mine===generation)loading.value=false}}
async function search(){const query:Record<string,string>={grain:grain.value};for(const k of dimensions.value)if(filters.value[k])query[k]=filters.value[k];if(range.value.length===2){query.start=range.value[0]!.toISOString();query.end=range.value[1]!.toISOString()}await router.replace({path:route.path,query});await load()}
const logs=computed(()=>({path:'/admin/call-logs',query:{...route.query,start:result.value?.start,end:result.value?.end}}))
watch(()=>route.fullPath,load,{immediate:true})
</script>
<template><div v-loading="loading"><PageHeader  :title="admin?'用量统计':'我的用量'"/><el-alert v-if="error" :title="error" type="error" :closable="false"/><div class="panel usage-filters"><el-input v-for="k in (advanced?dimensions:dimensions.filter(k=>['model','api_key_id'].includes(k)))" :key="k" v-model="filters[k]" :placeholder="labels[k]" style="width:155px"/><el-date-picker v-model="range" type="datetimerange" start-placeholder="开始时间" end-placeholder="结束时间"/><el-select v-model="grain" style="width:120px"><el-option label="按天" value="day"/><el-option label="按小时" value="hour"/></el-select><el-button type="primary" @click="search">查询</el-button><el-button @click="advanced=!advanced">{{advanced?'收起筛选':'更多筛选'}}</el-button><router-link v-if="admin&&result&&new Date(result.end).getTime()-new Date(result.start).getTime()<=31*86400000" :to="logs" class="usage-link">查看对应调用日志 →</router-link></div><template v-if="result"><div class="usage-cards"><div v-for="k in metrics" :key="k" class="usage-card"><span>{{labels[k]}}</span><strong>{{result.summary[k]==null?'不可用':Number(result.summary[k]).toLocaleString()}}</strong></div></div><p class="muted">成功 {{result.summary.success}} · 失败 / 取消 {{result.summary.failure}} · 活跃用户 {{result.summary.active_users}} · Token 字段不完整 {{result.summary.usage_unavailable}}</p><details class="usage-notes"><summary>统计口径与速率说明</summary><p class="muted">TTFT 仅包含观测到首个有效内容块的流式请求（{{result.summary.ttft_samples}} 个样本）。Tokens/s = 上游输出 Token ÷ 生成时长（{{result.summary.tps_samples}} 个样本）；非流式采用上游整包响应时长。均值按有效请求样本计算。Token 字段不完整的请求仍计入成功 / 失败统计，已上报字段继续计入用量。</p></details><div class="panel"><div class="toolbar"><h2>时间趋势</h2><el-select v-model="chartMetric" style="width:220px"><el-option v-for="k in chartMetrics" :key="k" :label="labels[k]" :value="k"/></el-select><span v-if="admin" class="muted">点击数据点查看对应时段调用日志</span></div><div ref="chartHost" style="height:300px;width:100%"></div><el-table :data="result.series" empty-text="所选区间暂无推理请求"><el-table-column :label="'显示时间 · '+branding.timezone" min-width="180"><template #default="s">{{formatDate(s.row.bucket)}}</template></el-table-column><el-table-column v-for="k in ['requests','success','failure','input_tokens','output_tokens','cached_tokens','total_tokens','average_ttft_ms','average_tokens_per_second']" :key="k" :label="labels[k]" min-width="130"><template #default="s">{{s.row[k]??'不可用'}}</template></el-table-column><template #empty><EmptyState title="所选区间暂无推理请求" description="检查筛选条件、时间范围或相关配置后重试。"/></template></el-table></div></template></div></template>
<style scoped>.usage-filters{display:flex;gap:12px;flex-wrap:wrap;align-items:center}.usage-cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin:24px 0}.usage-card{background:var(--surface);border:1px solid var(--line);border-radius:8px;padding:18px}.usage-card span{display:block;color:var(--muted);font-size:13px}.usage-card strong{display:block;font-size:26px;margin-top:10px;overflow-wrap:anywhere}.usage-link{color:var(--el-color-primary)}@media(max-width:1100px){.usage-cards{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:800px){.usage-cards{grid-template-columns:repeat(2,minmax(0,1fr))}}</style>
